### ISSUE TITLE
TypeError: Cannot read property 'file' of undefined

### ISSUE THREAD

**Issue by alegout** [duan602728596/gulp-terser#4]
+--------------------
+-- VERSIONS
+--------------------
+-- npm@6.2.1
+-- gulp@3.9.1
+-- gulp-terser@1.1.4
+--------------------

Hello,

I switched from gulp-uglifyes to gulp-terser but i got this error:

TypeError: Cannot read property 'file' of undefined
    at DestroyableTransform._transform (/%project_path%/node_modules/gulp-terser/lib/index.js:41:30)

Any clue?

Thank you very much,
Alban

**Comment by duan602728596** [comment]
@alegout Can you show me your version number and configuration?

**Comment by Dumkin** [comment]
I have exactly the same error

**Comment by alegout** [comment]
Simple example not working:

```
gulp.task('js-vendor', function() {
    return gulp.src('node_modules/jquery/dist/jquery.min.js')
        .pipe(terser())
        .pipe(gulp.dest('Resources/sources/tmp/js'));
});
```

Thank you,
Alban

**Comment by Dumkin** [comment]
I have exactly the same error. Tried with different settings. Just tried this standard version. The same mistake is everywhere

node version v10.10.0
npm version 6.4.1
gulp version 3.9.1
gulp-terser version 1.1.4

tried to create an empty project
```
const gulp = require('gulp');
const terser = require('gulp-terser');
 
function es(){
  return gulp.src('./src/index.js')
    .pipe(terser())
    .pipe(gulp.dest('./build'));
}
 
gulp.task('default', es);
```

```
W:\Dev\123>gulp
[19:18:43] Using gulpfile W:\Dev\123\gulpfile.js
[19:18:43] Starting 'default'...

events.js:167
      throw er; // Unhandled 'error' event
      ^
TypeError: Cannot read property 'file' of undefined
    at DestroyableTransform._transform (W:\Dev\123\node_modules\gulp-terser\lib\index.js:41:30)
    at DestroyableTransform.Transform._read (W:\Dev\123\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (W:\Dev\123\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:172:83)
    at doWrite (W:\Dev\123\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:428:64)
    at writeOrBuffer (W:\Dev\123\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:417:5)
    at DestroyableTransform.Writable.write (W:\Dev\123\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:334:11)
    at write (W:\Dev\123\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_readable.js:623:24)
    at flow (W:\Dev\123\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_readable.js:632:7)
    at DestroyableTransform.pipeOnReadable (W:\Dev\123\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_readable.js:664:5)
    at DestroyableTransform.emit (events.js:182:13)
Emitted 'error' event at:
    at DestroyableTransform.onerror (W:\Dev\123\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_readable.js:558:12)
    at DestroyableTransform.emit (events.js:182:13)
    at DestroyableTransform._transform (W:\Dev\123\node_modules\gulp-terser\lib\index.js:54:14)
    at DestroyableTransform.Transform._read (W:\Dev\123\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:184:10)
    [... lines matching original stack trace ...]
    at flow (W:\Dev\123\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_readable.js:632:7)
```

**Comment by alegout** [comment]
Maybe an issue in [gulpfile.js](https://github.com/duan602728596/gulp-terser/blob/master/gulpfile.js) when building terser?

**Comment by duan602728596** [comment]
@alegout @Dumkin It is ok now. This is my mistake, forgetting when there is no gulp-sourcemaps.

**Comment by Dumkin** [comment]
Worked? Thank you!

**Comment by alegout** [comment]
Work for me too! Thank you very much @duan602728596
